### ISSUE TITLE
progressBar needs little fixing

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#13]
-we should switch it to c++ standard (so use stringstreams etc instead of printfs)
-when dumping the output to a file the progress bar prints every progress step. its because of the time printing which changes very often and triggeres a reprint. this should be avoided
-while we are at it fixed the formatting and follow coding conventions

**Comment by hansgans** [comment]
switched to C++, no idea how to avoid the mess with log files. Basically you should to pipe stdout to a log file. The logging system does not contain the progress bar
