### ISSUE TITLE
Rework intensitiy and amplitude interfaces

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#130]
- **AmpIntensity**, **Amplitude**, **PartialAmplitude**, **AbstractDynamicalFunction** classes:
 There is a lot of code duplication here and some classes contain members that should not be there. We need slim and separate interfaces for intensities and amplitudes that unifies these classes
- **IncoherentIntensity** implements a lot of functionality that seems to belong to the LogLikelihood class

**Comment by hansgans** [comment]
Examples?

**Comment by spflueger** [comment]
> Examples?
- AbstractDynamicalFunction has a member DaughtersMasses and Names. They should not be there at all (and if they are there they should be more than just a pair)
- all of these classes have separate definitions for evaluate/intensity or the tree and parameter functions

**Comment by hansgans** [comment]
> > Examples?
>     * AbstractDynamicalFunction has a member DaughtersMasses and Names. They should not be there at all (and if they are there they should be more than just a pair)
Yes I agree on that. Those should be moved to BreitWigner and so on.

>     * all of these classes have separate definitions for evaluate/intensity or the tree and parameter functions
Well there are seperate definition since these are seperate functions.  `AmpIntensity` has only `intensity()` which is always a real valued function. Other classes which return a complex value have a function `evaluate()`.

**Comment by spflueger** [comment]
Yeah I think the same. Maybe I formulate it more precisely. So there should be a intensity interface, which only returns real values (doubles). Then there should be an amplitude interface which returns in turn std::complex<double>. I would separate these interfaces into separate classes (especially the amplitude one).
PartialDecay should then just inherit from this amplitude class. I know the evaluate function are not identical here and takes the position index variable. I have to think about this part a bit more. Its just not very pretty that we have 4 interfaces for function evaluation, all doing something very similar

A general point is: interface or abstract classes should only contain the bare minimum functionality to be as general as possible

**Comment by hansgans** [comment]
> Yeah I'm aware of that. Maybe I formulate it more precisely. So there should be a intensity interface, which only returns real values (doubles). Then there should be an amplitude interface which returns in turn std::complex. I would separate these interfaces into separate classes (especially the amplitude one).
> PartialDecay should then just inherit from this amplitude interface or in this case probably directly from Amplitude (since PartialDecay is probably an Amplitude, just a special one)
> 

Thats how it is implemented. PartialDecay is an interface class.

> AbstractDynamicalFunction is a bit more complicated, since the evaluate functions are not identical here and takes the additional position index variable. I have to think about this part a bit more. Its just not very pretty that we have 4 interfaces for function evaluation, all doing something very similar

We have 4 different Interfaces for 4 different things. I dont see you point here.

**Comment by spflueger** [comment]
No that's not how its implemented (btw: with PartialDecay I meant PartialAmplitude).
Look at PartialAmplitude, it defines a lot of identical interface functionality that is already defined in Amplitude...

**Comment by hansgans** [comment]
PartialAmplitude is not an Amplitude....

**Comment by spflueger** [comment]
And why is that? In my opinion it should be.
And even if it would not be an amplitude, the common denominator parts should be taken out into a separate class.

**Comment by hansgans** [comment]
An amplitude is a physical object, describing the transtition from an initial state to a final state. A PartialAmplitude describes a two body decay (which does not necessarily needs to be a physical quantity.

**Comment by spflueger** [comment]
First of all, PartialAmplitude should not be limited to two body decays, and as far as I see it also isn't (HelicityDecay is). Second in your example PartialAmplitude is also an amplitude, with an initial and final state. So I don't really get the point.
If I just compare both classes, the only differences I can see is the normalization and the prefactor in PartialAmplitude. Otherwise they are like identical.
I'm not sure we are on the same page. Since this needs a lot deeper discussion, we should continue this in a private meeting.
