### ISSUE TITLE
Install TBB

### ISSUE THREAD

**Issue by hansgans** [ComPWA/ComPWA#144]
Currently, the TBB repo is included in ComPWA. This is fine, except that it lacks an install routine. That means after `make install` binaries won't find TBB anymore. Additionally it would be great if a system wide installation could be used instead of the internal.

**Comment by hansgans** [comment]
It also seems that rerunning cmake breaks due to TBB

**Comment by spflueger** [comment]
> It also seems that rerunning cmake breaks due to TBB

How so? Can you elaborate this problem?

**Comment by spflueger** [comment]
> Currently, the TBB repo is included in ComPWA. This is fine, except that it lacks an install routine. That means after `make install` binaries won't find TBB anymore. Additionally it would be great if a system wide installation could be used instead of the internal.

Indeed the official tbb repo lacks convenient cmake features. If we still want to ship tbb with ComPWA, then I guess we have to refer to https://github.com/wjakob/tbb. But if we want to have the possibility to also use a system wide installation, it would be best to let the user install tbb himself.
