### ISSUE TITLE
Single source for the default particles

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#145]
Use and xml file to define the default particles. This can be read in and used by the python and c++ code. Currently the two versions being maintained is not good

**Comment by hansgans** [comment]
Thats a good idea as long as you find a way such that the default list is always found no matter if you run ComPWA from the build folder or after `make install`. And of course python also with needs to find it in any circustance.

**Comment by spflueger** [comment]
Yes of course. I think the best compromise between system compatibility and simplicity is having either an environment variable or installing the configuration file into a user config directory such as `~/.ComPWA/...`
