### ISSUE TITLE
apply fit result to model

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#150]
It has to be possible to read in a fit result and apply it to a model, so that the model is in the state as stated by the fit result.

**Comment by spflueger** [comment]
maybe we can combine this issue with issue #152

**Comment by hansgans** [comment]
I do not think we should combine this isseue with something else. It is the most urgent issue and should be solved as fast as possible.

**Comment by spflueger** [comment]
The pull request #204 almost covers this issue as well. Only the FitParameterList has to be converted to a `vector<double>`, which can be used to update the parameters of a Function.

**Comment by spflueger** [comment]
Has anyone worked or finished this? I would implement this really quick, since I need this part for the fit fractions.
