### ISSUE TITLE
Improve FitResult class and inheriting classes

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#152]
There is a lot of code overhead and casting going on. A redesign should be considered.

**Comment by spflueger** [comment]
I think the best solution would a simple container structure for storing the fit result information. Since this is also the purpose of the class, it suits this nicely. It would avoid all of the castings, and only this structure is needed. So the `Minuit2` and `Geneva` `FitResult` classes can be removed.
By introducing a `map<std::string, double/int/...>` within the new fit result the container struct, it would also be flexible enough for future modifications.

**Comment by hansgans** [comment]
The error estimate can be different between different minimization procedures (e.g. the covariance matrix is not necessarily calculated). That was is idea behind two different classes. But in principle I agree that many thing can be part of a common class. The covariance matrix could probably be inserted by the decorator pattern?

**Comment by spflueger** [comment]
> The error estimate can be different between different minimization procedures (e.g. the covariance matrix is not necessarily calculated).

I understand. But such information could be dynamically added to the fit result using a map-like STL container.

> The covariance matrix could probably be inserted by the decorator pattern?

No afaik. The decorator pattern adds functionality or behavior.

**Comment by hansgans** [comment]
A different way to estimate errors is a specific behavior, I would say.

**Comment by spflueger** [comment]
That true. That would be the second solution, which would be a FitResult interface, and implementations and decorators.
I personally decided against this solution, since the fit result is more an information storage then some object which has functionality.
