### ISSUE TITLE
A unique id for Event and DataPoint

### ISSUE THREAD

**Issue by zhang-jingqing** [ComPWA/ComPWA#198]
I propose to add a unique id (int or long int) to Event/DataPoint, which can be used to identify 
the unique event. It will be useful when debug. And it will be useful when some one wants to get a toy sample with proper detector simulation. For example, we have a true phsp MC sample and the corresponding 
reconstructed phsp MC sample, and the reconstructed phsp MC sample is a subset of the true
phsp MC sample, and same event in two sample have same id. Then we can use ComPWA to get a toy sample from true phsp MC sample. Then we extract the events which shared same 
unique id between the toy sample and the reconstructed sample. These extracted events should be the toy sample with detector simulation.

**Comment by hansgans** [comment]
The true PHSP sample should have the same size as the reconstructed sample, but a different phase space position. So the reconstructed sample is not a subset but the full set.

**Comment by spflueger** [comment]
I don't like the idea to introduce something for debug purposes. The debugger can handle that. But I can judge the physics point of view right now. I also thought what Peter said, that the two samples should be the same size.

**Comment by spflueger** [comment]
Feel free to reopen if this is still an issue
