### ISSUE TITLE
Improve the form factor code

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#205]
The current form factor design is not good.
There is a single function which receives a flag about which form factor to use, processed via a switch statement
- This bloats up this single function to something large and unreadable
- It is inconvenient to extend the function with a new form factor description
- It is an unnecessary slowdown
- It is not very flexible, because the arguments are the same for all of the form factors (even a simpler form factor would use only one argument, or a new form factor needs more arguments then presently stated).

The proposed solution is of course to have one function per form factor type and the switch statement is moved to the intensity construction, where a form factor type points to specific function. In order for this to be used within the function tree, the `FormFactorStrategy` has to be modified to receive the form factor type at construction and call the appropriate function. Here a lambda function or function object can help

**[Estimated effort: 2d]**

**Comment by weidenka** [comment]
We should consider @zhang-jingqing comment: https://github.com/ComPWA/ComPWA/pull/204#discussion_r314282863
