### ISSUE TITLE
Calculate error of MC integration

### ISSUE THREAD

**Issue by weidenka** [ComPWA/ComPWA#206]

**Comment by spflueger** [comment]
Just for reference https://en.wikipedia.org/wiki/Monte_Carlo_integration

**Comment by weidenka** [comment]
I implemented the calculation of the uncertainty. For one example model the uncertainty is smaller than the machine precision for 10^6 phsp events. But if I choose a different seed for the generation of the phsp sample the deviation is notably. Currently, I don't understand where is coming from.
