### ISSUE TITLE
ToDo in DalitzAnalysis

### ISSUE THREAD

**Issue by weidenka** [ComPWA/ComPWA#217]
* Flatte couplings are not printed in fitResult
* Plot components
* Load fit result

**Comment by spflueger** [comment]
A few thoughts regarding the flatte implementation: 
- The masses used in the couplings should be fit parameters and not constants.
- The coupling class can also be reduced to a struct or tuple of the coupling g and the two masses.
- The fit parameters (coupling and the two masses) have to be added to the ParameterList in the BuilderXML. This fixes the first point in the comment above

**Comment by weidenka** [comment]
fixed with #243
