### ISSUE TITLE
Increase cmake boost version compatibility

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#220]
**Describe the bug**
When using boost 1.70.0 (probably also above), the dynamic linking to boost libraries does not work anymore.

Boost comes with its own CMake config code now, which changes the previous default settings. `set(BUILD_SHARED_LIBS ON)` has to be used now.

**To Reproduce**
Try to compile ComPWA with boost 1.70.0

**Comment by weidenka** [comment]
Compiling with bosst 1.71 works for me

**Comment by spflueger** [comment]
I see. I guess it also has to do with the CMake Version. Which CMake do you use?

**Comment by spflueger** [comment]
We should delete our FindBoost file though, and instead use the one shipped with CMake

**Comment by spflueger** [comment]
Yes. That seems like a reasonable solution to me

**Comment by spflueger** [comment]
Btw, are you using the safe linking option?

**Comment by weidenka** [comment]
I use the default build settings

**Comment by weidenka** [comment]
What do you mean with a reasonable solution? To keep the FindBoost.cmake in the repository or to remove it?

**Comment by spflueger** [comment]
> I use the default build settings

I could not get 1.70.0 to work unless I made changes in the CMakeLists file. I guess I have to try it with boost 1.71 then, but I'm a bit puzzled why this works out of the box for you

**Comment by spflueger** [comment]
> What do you mean with a reasonable solution? To keep the FindBoost.cmake in the repository or to remove it?

To remove it. This is not our task, to maintain the compatibility of CMake and Boost. If you want to use a new boost, then you need to use a new CMake. That sounds good to me.

**Comment by weidenka** [comment]
I think it is not a big deal to update FindBoost.cmake from time to time.

**Comment by spflueger** [comment]
> Compiling with boost 1.71 works for me

Ok so boost 1.71 also does not work for me. The compilation works, but running the tests fails. This is problem I fixed with the small modifications in our `CMakeLists.txt` file

**Comment by spflueger** [comment]
All right, I tried various combinations now. For all these test I have removed the `FindBoost.cmake` file of the ComPWA project. These are my result:

1. boost 1.65.1: 
    - cmake 3.10.2 & NO changes in our top `CMakeLists.txt`: **compilation success, tests success**
    - cmake 3.15.3 & NO changes in our top `CMakeLists.txt`: **compilation success, tests success**
    - cmake 3.10.2 & WITH changes in our top `CMakeLists.txt`: **compilation success, tests success**
    - cmake 3.15.3 & WITH changes in our top `CMakeLists.txt`: **compilation success; tests success**

2. boost 1.70.0: 
    - cmake 3.10.2 & NO changes in our top `CMakeLists.txt`: **compilation fails**
    - cmake 3.15.3 & NO changes in our top `CMakeLists.txt`: **compilation fails**
    - cmake 3.10.2 & WITH changes in our top `CMakeLists.txt`: **compilation success, tests fail**
    - cmake 3.15.3 & WITH changes in our top `CMakeLists.txt`: **compilation success; tests success**

3. boost 1.71.0: 
    - cmake 3.10.2 & NO changes in our top `CMakeLists.txt`: **compilation success, tests fail**
    - cmake 3.15.3 & NO changes in our top `CMakeLists.txt`: **compilation success, tests success**
    - cmake 3.10.2 & WITH changes in our top `CMakeLists.txt`: **compilation success, tests fail**
    - cmake 3.15.3 & WITH changes in our top `CMakeLists.txt`: **compilation success; tests success**

Note that boost 1.71.0 does work without any changes using cmake 3.15.2.

Also I tried to use the `FindBoost.cmake` from cmake 3.15.2 in ComPWA, but then I get cmake errors. So this FindBoost is not compatible with other boost versions unless you make some modifications.

My conclusions from all of these results is, that my fixes in the CMakeLists.txt file are not good, since they only achieve higher compatibility for boost-1.70 when using a newer compiler. Furthermore the boost 1.70.0 seems troublesome itself and only works with some fixing on newer cmake versions. However old boost versions work nicely with old cmake versions and new boost versions work with new cmake versions.

As a result I would still remove the FindBoost.cmake file from ComPWA since this compatibility is managed by cmake + boost, and leave our CMakeLists file as it is.

**Comment by spflueger** [comment]
Postponed
