### ISSUE TITLE
Fix conflicts with tbb when building as static library

### ISSUE THREAD

**Issue by redeboer** [ComPWA/ComPWA#240]
Building with static libraries sometimes results in weird runtime behaviour (the executable keeps running) is you use more than one ComPWA module that implement some parallelisation from `tbb`. See [this travis job result](https://travis-ci.com/ComPWA/ComPWA/jobs/249466271#L1514) of [pull request 237](https://github.com/ComPWA/ComPWA/pull/237) in particular.

Actually, `tbb` strongly advises not to build static libraries, but we need to build ComPWA as static for pycompwa. @spflueger knows more about the details.

**Comment by spflueger** [comment]
I found a solution for this problem. The RPATH can be set to a relative path of its own location using $ORIGIN. This code snippet would be enough to link everything correctly

`SET(CMAKE_INSTALL_RPATH "$ORIGIN/:$ORIGIN/../lib")`

However I'm not sure if his will work on mac os x as well. @weidenka, could you give it a try with this?

**Comment by weidenka** [comment]
The problem with this solution is that the relative path is used w.r.t. the directory from which you execute the program. That means you can only run an executable from specific directories.

**Comment by spflueger** [comment]
Actually no. If you use relative paths yes, but not with `$ORIGIN`. Could you give this a try please, because it works fine for me

**Comment by weidenka** [comment]
Ah I see. For macOS the corresponding line is 
```
list(APPEND CMAKE_INSTALL_RPATH "@loader_path/../lib;@loader_path")
```
which needs to be included in `pycompwa`'s `CMakeLists.txt` as well.

**Comment by spflueger** [comment]
Ok. So the question is where we put this. In principle it would be enough to put this line into pycompwa CMakeLists. Or should we also use this setting for ComPWA itself?

**Comment by weidenka** [comment]
I think a fully relocatable library is nice. So we should put this also in CMakeLists.txt of ComPWA.
