### ISSUE TITLE
Parallelization of data generation

### ISSUE THREAD

**Issue by hansgans** [ComPWA/ComPWA#25]
The calculation of AmpSumIntensity is currently not thread safe, and therefore the generation of data can not be parallelised.

**Comment by spflueger** [comment]
is this fact still valid? The amplitude interface defines a const evaluate function, so i would assume that the data generation should be thread safe.

**Comment by hansgans** [comment]
Let me emphazise it **should** be thread safe but in prinziple I agree. Nevertheless, there is no functionality to parallelise it.

**Comment by spflueger** [comment]
i would try to take care of this tomorrow if thats all right with you
