### ISSUE TITLE
Performance issue with BuilderXML

### ISSUE THREAD

**Issue by weidenka** [ComPWA/ComPWA#263]
The example `DalitzAnalysis_D03K`(200k MC events, 1000 signal events) has a total runtime of 7min from which about 5min are spend on building the intensity. Most of the time is spend in `ComPWA::Physics::updateDataContainerContent`. @spflueger could you think of ways to improve this?

**Comment by spflueger** [comment]
Is this compiled with Release or Debug?

**Comment by weidenka** [comment]
Release

**Comment by spflueger** [comment]
Ok, which branch I have to look at to reproduce this? I just used upstream/master and the program ran through in about 1:40 min. However the fit also failed.

**Comment by weidenka** [comment]
upstream/master is fine. Make sure that `config.cfg` and `model.xml` from `Examples/DalitzAnalysis_D03K` are in your current working directory. To be fair, in this example the amplitude is build twice - a 'true model' and a 'fit model'. Anyway, its about 2:30min on my laptop which is a bit too long in my opinion, given the simple amplitude model and the total runtime of the example.

**Comment by spflueger** [comment]
So what does the 7min refer to?
>The example DalitzAnalysis_D03K(200k MC events, 1000 signal events) has a total runtime of 7min from which about 5min are spend on building the intensity

I see your point. I'm curious now what the runtime was from the beginning on? There are definitely possible improvements. The biggest improvement would be to only update the container content once. Currently the containers are updated for each normalization in the intensity, which is completely redundant. I just followed the previous code here and I remember there was an issue with the FunctionTree, that forced this update call on every normalization. I can check this real quick

**Comment by weidenka** [comment]
7min is the total runtime of the executable. Furthermore, I guess that the time spend in `updateDataContainerContent` depends on the number of MC events used for normalisation. 200k is a rather small number - for more realistic numbers that could be quite a large amount of time.

**Comment by spflueger** [comment]
Ok, so when I move the container filling to then end, and only do it once, the FunctionTree prints this error message several times.

> [ERROR] Inverse::execute() | Division by zero

But things are still working. So you get the same result and everything. The runtime decreases from 3:40min to 1:45 min (on my machine).

I don't understand why the FunctionTree evaluates the tree at this point. I don't think its necessary and I would assume that this can be removed. Then the division by zero error message would disappear and I would say this solves the problem.

**Comment by spflueger** [comment]
Ok I just removed those evaluations of the tree during the construction as well. That should solve it. See the PR #264
