### ISSUE TITLE
Improve header of the ASCII reader and make compatible with Pawian

### ISSUE THREAD

**Issue by redeboer** [ComPWA/ComPWA#280]
The current [`Ascii::readData`](https://github.com/ComPWA/ComPWA/blob/cb584cd0a661ba0c87d113e876edd168c964b30f/Data/Ascii/AsciiDataIO.hpp#L31) function can read Pawian-like momentum tuple files with and without a 'header' (see Doxygen comments for illustration of the format). However, there are a few issues with this:

* Current deduction of p,E vs E,p order of the momentum tuples is deduced by checking which of the 'order interepretation' leads to a positive invariant mass for the first momentum tuple. But this check is not a guarantee that the order interpretation is the correct one. So the order should be in the header as well.
* The header lacks units.
* `Pids: ...` would be better than `Pid: ...`,  `Pid: ...`, etc
* The format follows its own thought-up syntax, which should be avoided. Maybe formal YAML would be better (e.g. `Pids: [211, 421, -411]`). But then we would need to use a real third-party parser, so that users can actually use real YAML syntax.

To make matters more complicated, there is interest to have this header parser implemented in Pawian as well. Since the *aim of this reader is to make comparison between the two frameworks more easy*, decisions on this issue should be fine-tuned to each other.

**Comment by redeboer** [comment]
Note: there was an idea to allow the user to tell the `Ascii::readData` function how to interpret the data file by feeding it a `Kinematics` object (which contains the final state particles). Considering the remarks above, it's probably better to abandon that idea and to expect the user to supply a header in the data file.

**Comment by spflueger** [comment]
Yeah the header solution is better. Are there any news on this?

**Comment by redeboer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ASCII reader](https://trello.com/c/Pc8OMGkJ/9-ascii-reader)

**Comment by redeboer** [comment]
Fixed by https://github.com/ComPWA/ComPWA/pull/304
