### ISSUE TITLE
Precision of calculation

### ISSUE THREAD

**Issue by MathiasMichel** [ComPWA/ComPWA#30]
Use typedef, template otl for estimation calculations to enhance precision to e.g. long double only if necesarry

**Comment by spflueger** [comment]
We have a template interface `Function` now. So it would be possible to define a more precise one. The backends performing the calculations should also be templated to seamlessly handle other types. I think we already have a foundation to adapt to later on, if we need higher precision. I would close this issue, and it can be reopened if precision issues will occur.
