### ISSUE TITLE
multiple Kinematics

### ISSUE THREAD

**Issue by MathiasMichel** [ComPWA/ComPWA#31]
Up to now the Kinematics is a singleton so we can access it from different places without mixing things up. To enable combined analyzes we have to have multiple Kinematics, so either we "expand" the singleton to an abstract factory (still centralized) or we create Kinematic objects instead which are known to the amplitudes (more clear ownership)

**Comment by hansgans** [comment]
Singleton pattern is removed. Multiple Kinematics instances can be created now.
