### ISSUE TITLE
needed expert system functionality

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#32]
-make sure spin wave qn are easily extendable
-each decay node has to be able to require a separate set of conserved qn (currently its for the global decay tree only)
-implement g-parity
-also showing info about which qn are not conserved in decay, often has to be a combination (e.g. L and P) or (G and L and P)

**Comment by hansgans** [comment]
We should probably have a look on [http://www.gecode.org](url). And on `constraint satisfaction problems` in general.
