### ISSUE TITLE
Calculate phase space volume for general n-particle reactions

### ISSUE THREAD

**Issue by weidenka** [ComPWA/ComPWA#37]
- Hope we can do that analytically

**Comment by spflueger** [comment]
is this part crucial? What exactly has to be done here?

**Comment by hansgans** [comment]
It has to be calculated :). It is crucial if you want to combine data sets of different kinematica. Then, you need to add two likelihoods and the phsp volume is a scale factor.

**Comment by spflueger** [comment]
Hmm so I guess it should be done with hit&miss MC? Do we need it for the first release version?

**Comment by hansgans** [comment]
I think we should to this before any release. Hit&miss could be inaccurate. There is certainly an analytic way to do it.

**Comment by spflueger** [comment]
There seems to be a recursive analytic formula: http://theory.gsi.de/~knoll/Lecture-notes/1-kinematic.pdf p. 6f.

**Comment by redeboer** [comment]
Before I issue a merge request:
Draft to the solution can be found here ([hpp](https://github.com/redeboer/ComPWA/blob/450ce3d2331f776d47832a8e6465af7dc378146f/Physics/PhspVolume.hpp)/[cpp](https://github.com/redeboer/ComPWA/blob/450ce3d2331f776d47832a8e6465af7dc378146f/Physics/PhspVolume.cpp)/[test](https://github.com/redeboer/ComPWA/blob/450ce3d2331f776d47832a8e6465af7dc378146f/Physics/test/PhspVolumeTest.cpp)). Results agree with the [Mathematica file I added](https://github.com/redeboer/ComPWA/blob/e5fafec6053cae1ab7a5c4a251681c817ec0785f/Physics/test/PhspVolumeTest.nb), but I can't reproduce phasespace volume of [this file, line 253](https://github.com/redeboer/ComPWA/blob/450ce3d2331f776d47832a8e6465af7dc378146f/Examples/DalitzAnalysis_D0KsKK/model.xml#L253).

Note that there is only a numerical solutions if there are more than 2 particles in the final state. See the paper referred to by @spflueger, Eq. (51).
> There seems to be a recursive analytic formula: http://theory.gsi.de/~knoll/Lecture-notes/1-kinematic.pdf p. 6f.

**Comment by redeboer** [comment]
Have been testing recursive integration of [that paper](http://theory.gsi.de/~knoll/Lecture-notes/1-kinematic.pdf) with 𝑒⁺𝑒⁻→𝑛𝛾 with an improved algorithm ([hpp](https://github.com/redeboer/ComPWA/blob/3c1b0ca75c4d60295e8e7ad9c6a737c0022a98fb/Physics/PhspVolume.hpp)/[cpp](https://github.com/redeboer/ComPWA/blob/3c1b0ca75c4d60295e8e7ad9c6a737c0022a98fb/Physics/PhspVolume.cpp)/[test](https://github.com/redeboer/ComPWA/blob/3c1b0ca75c4d60295e8e7ad9c6a737c0022a98fb/Physics/test/PhspVolumeTest.cpp)). In that case, there is an analytical solution to Eq. (51):

* 2 photons: 2𝜋
* 3 photons: 𝜋²𝑠
* 4 photons: 𝜋³𝑠²/6
* 5 photons: 𝜋⁴𝑠³/72

We now use Riemann integration, but it would probably be more efficient to use hit & miss. Some benchmarks for the current Riemann implementation:

**𝐷⁰→𝐾𝐾𝐾 (increasing iterations)**

| Iterations | CPU time (ms) | % difference |
| ----------:|:------------- |:------------ |
|         10 | 0.0277        | 3.4          |
|        100 | 0.0235        | 0.11         |
|      1,000 | 0.341         | 3.9·10⁻³     |
|     10,000 | 5.10          | 5.2·10⁻⁴     |
|    100,000 | 36.2          | 4.2·10⁻⁴     |

**𝑒⁺𝑒⁻→𝑛𝛾 (increasing 𝑛)**

| 𝑛 photons | CPU time (ms) | % difference |
| ---------:|:------------- |:------------ |
|     2 𝛾ʼs | 0.006         | NA           |
|     3 𝛾ʼs | 0.121         | 0.1          |
|     4 𝛾ʼs | 150           | 0.1          |
|     5 𝛾ʼs | 115·10³       | 0.1          |

(The relative difference is weird indeed)
