### ISSUE TITLE
Disable/Enable packages is not working

### ISSUE THREAD

**Issue by hansgans** [ComPWA/ComPWA#4]
Changing variables build_<package> in Jamroot has no effect.

**Comment by spflueger** [comment]
I will have a look at it... Thought it was working when I checked it. Probably will take care of it tomorrow.

**Comment by spflueger** [comment]
Hmm it was working for me. I assume that you changed the values in the lines from 1 to 0. This had no effect. Only commenting the whole line. Now I changed it so that a commented line and a value of 0 disable the module and visa versa. Let me know if things a not working...
