### ISSUE TITLE
Add plotting module using histogrammar

### ISSUE THREAD

**Issue by hansgans** [ComPWA/ComPWA#60]
See https://github.com/histogrammar/histogrammar-cpp. Unfortunately the cpp codes does not seem to be very mature.

**Comment by spflueger** [comment]
For plotting I would suggest to use python i.e matplotlib? ROOT has a python interface and rootpy makes that a bit nicer

**Comment by hansgans** [comment]
histogrammar is supposed to be some kind of standard for histogram definition. The plotting itself could still be done in matplotlib. The advantage could be that you can create and save histograms from C++ code and load it in a python script.

**Comment by spflueger** [comment]
Oh ok, so a kind of Root alternative

**Comment by spflueger** [comment]
Don't think we need this. The data is written out in various formats (currently only ROOT) and then import to the python plotting module, which is used for the visualization. I dont see how histogrammar facilitates anything here. I would close the issue
