### ISSUE TITLE
common documentation including both c++ and python code

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ComPWA#86]
use doxygen sphinx and breathe to combine the two docs

**Comment by hansgans** [comment]
I miss some stuff in the documentation of the C++ code:
* List of classes (w/o namespaces)
* Browsable list of name spaces (e.g. show all objects under ComPWA::Physics)
* Links to source code (a link to the cpp file)

**Comment by spflueger** [comment]
Maybe consider using [exhale](https://github.com/svenevs/exhale)

**Comment by spflueger** [comment]
This issue is resolved with the splitting of the python code into a separate project [pycompwa](https://github.com/ComPWA/pycompwa) (#227). For ComPWA we use the readmes and doxygen, while pycompwa uses readmes and sphinx.
