### ISSUE TITLE
Normalization of IncoherentIntensity

### ISSUE THREAD

**Issue by zhang-jingqing** [ComPWA/ComPWA#92]
If the initial state is polarized(i.e., we can distinguish the polarization of the initial state), 
the normalization of the InchoerentIntensities should done independent.
If the initial state is not polarized(i.e., we can not distinguish the polarization of the initial state),
the normalization of the IncoherentIntensities should be same, i.e., the denominator is
sum of all possible incoherentIntensities)

**Comment by spflueger** [comment]
I discussed this a bit with @hansgans and it depends on the "fit fractions" how to normalize the result. Let me clarify the problem a little I define the incoherent intensity I = c1*I1 + c2*I2 + c3*I3
1.  The currently implemented normalization
I_norm = I1/int(I1) + I2/int(I2) + I3/int(I3) -> int(I_norm) = 3
Actually it normalizes all of the coherent intensities within and not the incoherent intensity. It takes away all of the relative normalizations between the coherent intensities I1,2,3 and makes them all equally strong. The fit parameters c1,2,3 would give the relative strengths of these coherent intensities. However the fit fractions would include all normalization effects like phase space factors, branching fractions, production strengths, spin related factors.
2. The suggested normalization in this issue
I_norm = (I1+I2+I3)/(int(I1+I2+I3) -> int(I_norm) = 1
Apart from the term normalization actually making sense here, the relative strengths of the individual terms stay the same after and before the normalization. Then the fit parameters c1,2,3 would only resemble the production strength and branching fractions of that coherent intensity.

I think we can discuss this here a bit further in the next days, what the best way to normalize would be. But to me the second option is more intuitive and I would assume it is also easier to calculate the physically interesting fit fractions from these c1,2,3 parameters later on.

**Comment by hansgans** [comment]
Neither of the options is wrong. I'm in strong support for the first option since it is way easier to calculate the variables of interest (fit fractions). This is the method currently implemented. I will close the issue for now. If discussion is still needed we can reopen it.
